{
  "ms excel": "microsoft excel",
  "excel": "microsoft excel",
  "ms word": "microsoft word",
  "powerpoint": "microsoft powerpoint",
  "comm skills": "communication skills",
  "communication skill": "communication skills",
  "interpersonal skill": "interpersonal skills",
  "teamwork": "team player",
  "team player": "team player",
  "problem solving skills": "problem solving",
  "customer services": "customer service",
  "auto cad": "autocad",
  "artificial intelligence": "machine learning",
  "ml": "machine learning",
  "nlp": "natural language processing",
  "pr": "public relations",
  "hr": "human resources",
  "bi": "business intelligence",
  "sql server": "sql",
  "ms sql": "sql",
  "javascript": "java script"
}
